# Generated by Django 2.1.3 on 2018-11-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subj_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('sub_sem', models.CharField(choices=[('Sem-I', 'Semester One'), ('Sem-II', 'Semester Two'), ('Sem-III', 'Semester Three'), ('Sem-IV', 'Semester Four'), ('Sem-V', 'Semester Five'), ('Sem-VI', 'Semester Six')], max_length=10)),
                ('course', models.CharField(choices=[('MCS', 'Masters in Computer Science'), ('MCA', 'Masters in Comuter Applications')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
