# Generated by Django 2.1.3 on 2018-11-13 14:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asmt_no', models.PositiveSmallIntegerField()),
                ('announcement_date', models.DateTimeField(default=datetime.date(2018, 11, 13))),
                ('due_date', models.DateTimeField(default=datetime.date(2018, 11, 13))),
                ('asmt_group', models.PositiveSmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subjects')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('cid', 'teacher_id')},
        ),
    ]
