# Generated by Django 2.1.3 on 2018-11-13 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_auto_20181113_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teacher_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('subject', 'asmt_no')},
        ),
    ]
