# Generated by Django 2.1.3 on 2018-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20181113_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='announcement_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
