# Generated by Django 2.1.3 on 2018-11-13 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20181113_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='announcement_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subjects'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
