# Generated by Django 2.1.3 on 2018-11-12 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('MCS', 'Masters in Computer Science'), ('MCA', 'Masters in Comuter Applications')], max_length=3)),
                ('phone', models.IntegerField(default=0)),
                ('semester', models.CharField(choices=[('Sem-I', 'Semester One'), ('Sem-II', 'Semester Two'), ('Sem-III', 'Semester Three'), ('Sem-IV', 'Semester Four'), ('Sem-V', 'Semester Five'), ('Sem-VI', 'Semester Six')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
