# Generated by Django 2.1.3 on 2018-11-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181112_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='phone',
            new_name='rollno',
        ),
    ]
